# Generated by Django 3.1.14 on 2022-12-13 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20221213_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='appeared_at',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='disappeared_at',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
